version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    command: [ "pnpm", "dev" ]

  app-production:
    build:
      context: .
      target: production
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
    command: [ "pnpm", "preview" ]
