name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run linting
      - name: Run ESLint
        run: pnpm lint

      # Check if the project compiles
      - name: Run TypeScript build
        run: pnpm build
